### PR TITLE
increase the version of the windows server

### PR DESCRIPTION
**Pull request by detnon**
increase the version of the windows server to `Windows_Server-2016-English-Core-Base-2021.06.09`, as the previous AMI `Windows_Server-2016-English-Core-Base-2021.04.14` has been removed

### CODE REVIEW

**Review by danjoneslf — COMMENTED** [review]
Is it possible to wildcard this to `Windows_Server-2016-English-Core-Base-*` or something so we don't have to keep changing it?

**Comment by detnon** [comment]
> Is it possible to wildcard this to `Windows_Server-2016-English-Core-Base-*` or something so we don't have to keep changing it?

How will terraform know which version to spin up?

**Comment by danjoneslf** [comment]
> How will terraform know which version to spin up?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#most_recent

**Comment by detnon** [comment]
> > How will terraform know which version to spin up?
>
> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#most_recent

Understood! 

Can i get a review plz?

**Review by danjoneslf — APPROVED** [review]
Have you checked it works?

**Pull request merged**
